#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def recur(num1, num2, total):
  num3 = num1 + num2
  if num3 > 4000000:
    print total
  else:
    if num3 % 2 == 0:
      recur(num2, num3, total+num3)
    else:
      recur(num2, num3, total)

recur(1, 1, 0)
